### ISSUE TITLE
CALL_ARM_SYSTEM_INIT isn't defined for the assembler

### ISSUE THREAD

**Issue by svijsv** [ThomasGravekamp/STM32-base#22]
CALL_ARM_SYSTEM_INIT is checked in startup_common.s which is compiled by the assembler, but it's defined for the C preprocessor. Adding '-Wa,--defsym,CALL_ARM_SYSTEM_INIT=1' to the flags fixes the issue.

**Comment by ThomasGravekamp** [comment]
Thank you for reporting this issue. I will look into this as soon as I've got the time to do so.
