### ISSUE TITLE
RobotDyn BlackPills do have a 5V protection

### ISSUE THREAD

**Issue by rico666** [ThomasGravekamp/STM32-base#25]
The text for the 

https://stm32-base.org/boards/STM32F103C8T6-RobotDyn-Black-Pill

claims

_The +5V pins on this board are directly connected to the +5V pin of the USB connector. There is no protection in place. Do not power this board through USB and an external power supply at the same time._

which seems to be copypasta from the F103 blue pill text. In fact, the RobotDyn black pills do have a diode between the internal 5V rail and the USB 5V - even the cheap APM32F103 clones (same design, just a different clone MCU):

https://robotdyn.com/pub/media/SM-00000243==APM32F103CB(128KB)-ARM32M3-BP/Schematic==SM-00000243==APM32F103CB(128KB)-ARM32M3-BP.pdf

**Comment by ThomasGravekamp** [comment]
Thanks for bringing this to my attention. I've fixed it.
