### ISSUE TITLE
Wrong crystal info for STM32F407VET6 mini

### ISSUE THREAD

**Issue by jcw** [ThomasGravekamp/STM32-base#26]
On the page for "vcc-gnd.com STM32F407VET6 mini", HSE is listed as being 8 MHz.
As the image shows, the crystal is actually a 25 MHz unit.

**Comment by ThomasGravekamp** [comment]
Thanks for bringing this to my attention. I've fixed the issue: https://github.com/STM32-base/STM32-base.github.io/commit/3121c3f591c2e803550ce01cda9d1cc9609a5d56
